QeAColors/Models/Color.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QeAColors.Models
{
    public enum Color
    {
        Azul = 1,
        Vermelho = 2,
        Verde = 3,
        Amarelo = 4
    }
}

QeAColors/Models/Player.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QeAColors.Models
{
    public class Player
    {
        public int CurrentQuestion { get; set; } = 0;
        public List<Result> Results { get; set; } = new List<Result>();
    }
}

QeAColors/Models/Question.cs
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

namespace QeAColors.Models
{
    public class Question
    {
        public string File { get; set; }
        public string Description { get; set; }
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public Color Color { get; set; }
    }
}

QeAColors/Models/Result.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QeAColors.Models
{
    public class Result
    {
        public Result()
        {
            DateStart = DateTime.Now;
            DateEnd = DateTime.MaxValue;
            Answers = new List<Color>();
            Questions = new List<Question>();
        }

        public DateTime DateStart { get; set; }
        public DateTime DateEnd { get; set; }
        public List<Question> Questions { get; set; } = new List<Question>();
        public List<Color> Answers { get; set; } = new List<Color>();
        public int CountResult {
            get => Questions.Select((x, i) => new { c = x.Color, index = i })
                            .Count(y => y.c == this.Answers.ToArray()[y.index]);
        }
    }
}

QeAColors/Controllers/GameController.cs
using System.Text.Json;
using QeAColors.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QeAColors.Controllers
{
    public class GameController : Controller
    {
        // GET: Game Question
        public ActionResult Index()
        {
            if (Session["Player"] == null)
            {
                return RedirectToAction("../Home");
            }

            if (Session["Questions"] == null)
            {
                Session["Questions"] = LoadQuestions();
            }

            var questions = (List<Question>)Session["Questions"];
            var player = (Player)Session["Player"];

            if (player.CurrentQuestion > questions.Count - 1)
            {
                Response.Redirect("~/Results");
                return null;
            }

            return View(questions[player.CurrentQuestion]);
        }

        // POST: Game Next
        [HttpPost]
        [Route("Next")]
        public ActionResult Next(int awnser)
        {
            try
            {
                var questions = (List<Question>)Session["Questions"];
                var player = (Player)Session["Player"];
                var currentQuestion = questions[player.CurrentQuestion];
                var currentAwnser = (Color)(awnser);

                if (player.Results == null)
                {
                    player.Results = new List<Result>();
                }
                if (player.Results.Count() == 0)
                {
                    player.Results.Add(new Result());
                }

                var lastResult = player.Results.LastOrDefault();
                lastResult.Questions.Add(currentQuestion);
                lastResult.Answers.Add(currentAwnser);
                if (player.CurrentQuestion == questions.Count() - 1)
                {
                    lastResult.DateEnd = DateTime.Now;
                }
                player.CurrentQuestion++;
                player.Results[player.Results.Count - 1] = lastResult;
                Session["player"] = player;

                return (lastResult.DateEnd == DateTime.MaxValue) ? RedirectToAction("../Game") : RedirectToAction("../Home/Results");
            }
            catch
            {
                return RedirectToAction("../");
            }
        }

        public static IEnumerable<Question> LoadQuestions()
        {
            string jsonString = System.IO.File.ReadAllText("C:\\Game\\Questions.json");
            return JsonSerializer.Deserialize<List<Question>>(jsonString);
        }

    }
}

QeAColors/Controllers/HomeController.cs
using QeAColors.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QeAColors.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (Session["player"] == null)
            {
                Session["player"] = new Player();
            }
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult Results()
        {
            if (Session["player"] == null)
            {
                Response.Redirect("Index");
            }
            var results = (Player)Session["player"];
            return View(results.Results);
        }

        public ActionResult New()
        {
            if (Session["player"] == null)
            {
                Response.Redirect("Index");
            }

            if (Session["Questions"] == null)
            {
                Session["Questions"] = Controllers.GameController.LoadQuestions();
            }

            var questions = (List<Question>)Session["Questions"];
            var player = (Player)Session["Player"];
            if (player.CurrentQuestion > questions.Count - 1)
            {
                player.Results.Add(new Result());
            }
            else
            {
                player.Results[player.Results.Count-1] = new Result();
            }
            player.CurrentQuestion = 0;
            Session["Player"] = player;
            return RedirectToAction("../Game/Index");
        }
    }
}

QeAColors/Views/Game/Index.cshtml
@model QeAColors.Models.Question

@{
    ViewBag.Title = "Pergunta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.2.min.js" type="text/javascript"></script>
<script src="http://ajax.aspnetcdn.com/ajax/modernizr/modernizr-2.0.6-development-only.js" type="text/javascript"></script>

<div class="form-horizontal">
    <div class="form-group">
        <div class="col-md-10">
            <audio id="audio" autoplay controls>
                <source src="@Url.Content("~/Audio/"+Model.File)" type="audio/mp3">
                Seu navegador não suporta o elemento de áudio.
            </audio>
            @using (Html.BeginForm())
            {
                @Html.DisplayTextFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            }
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <div class="row">
                <div class="col-md-6">
                    @using (Html.BeginForm("Next", "Game", FormMethod.Post))
                    {
                        @Html.Hidden("awnser", "1")
                        <input type="submit" value="" class="btn btn-primary" style="width:300px;height:150px;" />
                    }
                </div>
                <div class="col-md-6">
                    @using (Html.BeginForm("Next", "Game", FormMethod.Post))
                    {
                        @Html.Hidden("awnser", "2")
                        <input type="submit" value="" id="2" class="btn btn-danger" style="width:300px;height:150px;" />
                    }
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    @using (Html.BeginForm("Next", "Game", FormMethod.Post))
                    {
                        @Html.Hidden("awnser", "3")
                        <input type="submit" value="" id="3" class="btn btn-success" style="width:300px;height:150px;" />
                    }
                </div>
                <div class="col-md-6">

                    @using (Html.BeginForm("Next", "Game", FormMethod.Post))
                    {
                        @Html.Hidden("awnser", "4")
                        <input type="submit" value="" id="4" class="btn btn-warning" style="width:300px;height:150px;" />
                    }
                </div>
            </div>
        </div>
    </div>

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QeAColors/Views/Game/View.cshtml
@model IEnumerable<QeAColors.Models.Question>

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.File)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.File)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

QeAColors/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    Serviço Nacional de Aprendizagem Industrial - SENAI<br />
    Fulano<br />
    Sicrano<br />
</address>

<address>
    <strong>Contato:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
</address>

QeAColors/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Perguntas e Resposta em Cores</h1>
    <p class="lead">Trabalho da Segurança do Trabalho Noturno em Parceria com Desenvolvimento de Sistemas Noturno</p>
    <p><a href="/Game" class="btn btn-success btn-lg">Iniciar ▶️</a></p>
</div>

QeAColors/Views/Home/Results.cshtml
@model IEnumerable<QeAColors.Models.Result>

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>
    Resultados
    @using (Html.BeginForm("New", "Home", FormMethod.Get))
    {
        <input type="submit" value="Novo Jogo ▶️" class="btn btn-success" />
    }
</h2>

<table class="table">
    <tr>
        <th>Início</th>
        <th>Fim</th>
        <th>Pontos</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@item.DateStart.ToShortTimeString()</td>
        <td>@item.DateEnd.ToShortTimeString()</td>
        <td>@item.CountResult</td>
    </tr>
}

</table>

QeAColors/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início ▶️", "Index", "Home")</li>
                    <li>@Html.ActionLink("Resultados 🏆", "Results", "Home")</li>
                    <li>@Html.ActionLink("Contato 😊", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Serviço Nacional de Aprendizagem Industrial - SENAI</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>